#!/bin/sh
## This script starts aesdsocket application in daemon mode with -d option
## It also stop the application through SIGTERM for graceful exit
## Author: Phuoc NGUYEN

RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
NC="\033[0m" # No Color

# Define the path to the application
APP_NAME="aesdsocket"
APP_PATH="/usr/bin/${APP_NAME}"
APP_ARGS="-d"  # Arguments for your application
MODULE_NAME="aesdchar"

start() {
    printf "${GREEN}Install ${MODULE_NAME} module${NC}\n"
    modprobe $MODULE_NAME
    printf "${GREEN}Starting ${APP_NAME}...${NC}\n"
    start-stop-daemon -S -n $APP_NAME -a $APP_PATH -- $APP_ARGS
    if [ $? -eq 0 ]; then
        printf "${GREEN}${APP_NAME} started successfully.${NC}\n"
    else
        printf "${RED}Failed to start ${APP_NAME}.${NC}\n"
    fi
}

stop() {
    printf "${BLUE}Stopping ${APP_NAME} and ${MODULE_NAME}...${NC}\n"
    start-stop-daemon -K -n $APP_NAME --signal TERM
    if [ $? -eq 0 ]; then
        printf "${BLUE}${APP_NAME} stopped successfully.${NC}\n"
    else
        printf "${RED}Failed to stop ${APP_NAME}.${NC}\n"
    fi
    rmmod $MODULE_NAME
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        printf "${YELLOW}Usage: $0 {start|stop}${NC}\n"
        exit 1
        ;;
esac

exit 0
