#!/bin/sh
## This script starts aesdsocket application in daemon mode with -d option
## It also stop the application through SIGTERM for graceful exit

# Define the path to the application
APP_PATH="/usr/bin/aesdsocket" # in target
APP_PATH="./aesdsocket" # in host - for testing purpose

start() {
    printf "\033[1;32mStarting aesdsocket...\033[0m\n"
}

stop() {
    printf "\033[1;34mStopping aesdsocket...\033[0m\n"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        printf "\033[1;33mUsage: $0 {start|stop}\033[0m\n"
        exit 1
        ;;
esac

exit 0
